// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/GuessInput.tsx";
import * as $$1 from "./islands/GuessList.tsx";
import * as $$2 from "./islands/PatternGuessing.tsx";
import * as $$3 from "./islands/RegexleGame.tsx";
import * as $$4 from "./islands/SenteceGuessing.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/GuessInput.tsx": $$0,
    "./islands/GuessList.tsx": $$1,
    "./islands/PatternGuessing.tsx": $$2,
    "./islands/RegexleGame.tsx": $$3,
    "./islands/SenteceGuessing.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
